version: '2'
services:
  nationalparks-rest:
    image: nationalparks-rest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - DBHOST=192.168.3.230
      - DBPORT=3306
      - HTTPHOST=0.0.0.0
      - HTTPPORT=8080
