version: '2'
services:
  nationalparks-rest:
    image: nationalparks-rest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      # See config.sh for setting these values.  Apply the environment variables with "source config.sh" before
      # running "docker-compose up"
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - DBHOST=${DBHOST}
      - DBPORT=${DBHOST}
      - HTTPHOST=${HTTPHOST}
      - HTTPPORT=${HTTPPORT}
