apiVersion: v1
kind: Service
metadata:
  labels:
    io.imbm.service: nationalparks-rest
  name: nationalparks-rest
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.imbm.service: nationalparks-rest
status:
  loadBalancer: {}
