apiVersion: v1
kind: Service
metadata:
  name: nationalparks-rest-external
  namespace: nationalparks
spec:
  type: LoadBalancer
  selector:
    io.imbm.service: nationalparks-rest
  ports:
    - port: 80
      targetPort: 8080